### ISSUE TITLE
Create wai sdg webpage

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#144]
Need :
A webpage with url wai-eth.tc.akvo.org
In the page embed the following 3 Lumen dashboards in 3 tabs
WASH In Schools - https://washsdg.akvolumen.org/s/t40hKgei-f0
WaterPoint - https://washsdg.akvolumen.org/s/j8RYV9KkWco
WASH in Health Facilities - https://washsdg.akvolumen.org/s/Bq0eSnJBWvM

**Comment by dedenbangkit** [comment]
@iperdomo to register the subdomain.

**Comment by iperdomo** [comment]
@dedenbangkit http://wai-eth.tc.akvo.org/ is up

**Comment by dedenbangkit** [comment]
@wayangalihpratama status?

**Comment by joycarpediem** [comment]
@wayangalihpratama , use this logo https://wash-alliance.org/wp-content/uploads/sites/36/2016/06/dwa_logo_tagline_color_small-1.png
