### ISSUE TITLE
Clean up data visuals in the 2scale dashboard

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#147]
Ex: Select Mali in the Partnerships tab. Empty visuals are displayed.
Also the search panel is not aligned

**Comment by dedenbangkit** [comment]
@joycarpediem to review

**Comment by joycarpediem** [comment]
@dedenbangkit change not implemented for all visuals 
![screencapture-2scale-test-tc-akvo-org-partnership-2020-06-16-14_28_26](https://user-images.githubusercontent.com/4419787/84739212-c5d62380-afdd-11ea-8e65-8a3b59f40c56.png)

**Comment by dedenbangkit** [comment]
Solved @joycarpediem clear your cache
