### ISSUE TITLE
Change column selection in database tab

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#150]
Currently the database tab the user needs to individually deselect column. Since the number of columns can be very large , this will become a cumbersome exercise. We should add the possibility to add column t view rather than remove. Maybe a Select/Deselect all will do the job

**Comment by dedenbangkit** [comment]
But what are the default columns to show for each questionnaire @joycarpediem ?

**Comment by joycarpediem** [comment]
First 10 questions excluding meta data

**Comment by dedenbangkit** [comment]
Ref fe44ab8
