### ISSUE TITLE
Add global and Uganda covid19 stats to landing page 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#165]

**Comment by dedenbangkit** [comment]
Reminder:

- Issue for Flumen team: FlowApi doesn't return **surveyName** for **surveyGroupId: 998504001** in **wai** instance. **Alternative solution**:
https://github.com/akvo/akvo-tech-consultancy/blob/46888ddc67a14df848674709fdd7e98483f4e842/sites/unicef-uganda-5w/app/Http/Controllers/Api/InitController.php#L39

- Too many nested functions in (e.g: [InitFunctions.php](https://github.com/akvo/akvo-tech-consultancy/blob/develop/sites/unicef-uganda-5w/app/Http/Controllers/Api/InitController.php)). I  will make changes to all Console as what I did to [FakerController.php](https://github.com/akvo/akvo-tech-consultancy/blob/develop/sites/unicef-uganda-5w/app/Http/Controllers/Api/FakerController.php), then @wayangalihpratama will implement the changes to Kenya also.
