### ISSUE TITLE
Akvo RSR Custom Report Generator

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-tech-consultancy#21]
## List of API

| Usage | Endpoint | List of Important Data |
|--|--|--|
| Dropdown, Table Headers | [https://rsr.akvo.org/rest/v1/results_framework/?project=7283](https://rsr.akvo.org/rest/v1/results_framework/?project=7283)  | Result Title, Child Projects, Parent Project, Indicator Title, Dimension Name, Dimension Value, Indicator Periods, Baseline Year |
| Table Value | [https://rsr.test.akvo.org/rest/v1/indicator_period/?limit=100&format=json&indicator__result__project=7283](https://rsr.test.akvo.org/rest/v1/indicator_period/?limit=100&format=json&indicator__result__project=7283)  | Disaggregation and Disaggregation Target, Period Start, Period End |

## Output Report

![Image of Results](https://raw.githubusercontent.com/akvo/akvo-tech-consultancy/master/sites/akvo-rsr-appsa/images/table-results.png)
- Output: All Children Projects except Cardesa.
- PDO Report: Cardesa and its children.

UI
- Dropdown Selector: Whatever we select the results dropdown, period will verify to shows the longest indicator period options.
- Period date validator for results indicator: ``` <indicator_period_startdate/indicator_period_enddate><indicator_id>[list_of_indicator_period_startdate/list_of_indicator_periodenddate]```

# Requirements and Feature Requests 

- RSR Deployment on SEAP Office Local Server.
- Sync RSR Production to Develop to get the new features of development product along with the project schema that Anabelle set.
- Disaggregation Data (Dimensions) doesn't have a clear example JSON Schema unless we fill the data manually.
- List of disaggregation contributors (disaggregation value on child projects). **TBC**

**Comment by joycarpediem** [comment]
-[] Enable validations on clicking generate report (project selected, time period selected, country selected)

**Comment by dedenbangkit** [comment]
- [ ] Editing posted comments.
- [ ] Grouping rows view for Print & PDF.
- [ ] Error Notification for saving empty comments.

---------------------------------

Bugs:

- [ ] Axios double post, handling events on request time out.

**Comment by joycarpediem** [comment]
- [ ] Handle percentage indicators
- [ ] Editing posted comments.
- [ ] Grouping rows view for Print & PDF.

**Comment by dedenbangkit** [comment]
- [] The values at the indicator level should reflect the ‘actual value’ of the indicator in RSR and should not be a calculation based on disaggregations. (Reason: sometimes disaggregations might be missing or are incorrect and it makes it easier to handle percentage actual values).

- [] Program totals for targets and actuals in case of percentage indicators should be the average (regardless of what nominator and denominator are there). So Malawi: 10%, Zambia: 20 %, Mozambique: 30 %, will become 20% average.

- [] Put the actual values for indicators in the same row as indicator title in the report. Comment can go a row lower (if needed for space) but relates to the indicator level

- [] Comment box is currently ending up in title in RSR (limited characters). Make sure to link the comment box on the indicator to comment box on RSR. The title field for comment in the report generator is not needed.

- [] The disaggregated values do not have to be clickable, because there are no comments on disaggregations only on total actual value. For total actual value, only the actual value comment has to be displayed. You can remove the overview of disaggregations in the pop-up.

**Comment by joycarpediem** [comment]
- [ ] Grouping rows view for Print & PDF. Project/Indicator/Dimension should appear only once in their group
- [ ] Country filter not working
- [ ] PDF reports does not show Target and actuals labels
- [ ] Clicking on PDO 1 target and total shows only malawi's values. It should show all comments for all countries
