### ISSUE TITLE
reloading saved form throws error

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#213]
<img width="966" alt="Screenshot 2020-08-05 at 2 05 55 PM" src="https://user-images.githubusercontent.com/4419787/89377681-e5a7df00-d724-11ea-9195-15e67aa39e06.png">

**Comment by dedenbangkit** [comment]
@wayangalihpratama you make changes to this function:

https://github.com/akvo/akvo-tech-consultancy/blob/dac2e5f8bfe9d5d2736a318ec1ef34f09137e46e/sites/2scale/app/Libraries/FlowApi.php#L51-L68

This was to read this example endpoint: 
https://tech-consultancy.akvotest.org/akvo-flow-web-api/form-instance/91966ec8-f7b0-4698-b6f6-e1553024be14

I'm afraid it will break any changes you made, please revert the endpoint config with this line:
https://github.com/akvo/akvo-tech-consultancy/blob/dac2e5f8bfe9d5d2736a318ec1ef34f09137e46e/sites/2scale/config/akvo.php#L14

maybe the next time we have to do _git blame the file_ before making changes to it.

**Comment by dedenbangkit** [comment]
![Screen Shot 2020-08-07 at 1 13 19 AM (2)](https://user-images.githubusercontent.com/3245109/89567197-77aa0780-d84b-11ea-8402-012d2303c07c.png)

@joycarpediem this is the result when I hardcode the following lines directly from the server.

-----------------
https://github.com/akvo/akvo-tech-consultancy/blob/dac2e5f8bfe9d5d2736a318ec1ef34f09137e46e/sites/2scale/app/Libraries/FlowApi.php#L53

my endpoint is expecting the backend to read this URL ya:
@wayangalihpratama : ```$url = 'https://tech-consultancy.akvotest.org/akvo-flow-web-api/form-instance/' . $id;```
