### ISSUE TITLE
UNEP Testing - Joy

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#216]
## Overview Tab
- [x] There are 2 North America in the Region Filter
- [x] Add zoom button to map
- [x] Now once you click on a country on the map , the country gets selected . To go back to "All Countries" , you need to click on the same country. This is an issue when the countries are small. Go back to "All Countries" on clicking anywhere on the map
- [x] Hide the print button
- [x] Rethink the tree chart . Right now the interaction is very clumsy. For all tree charts
- [x] Add more visuals to the overviews tab

## Reports Tab
- [x] Add serial number to the table
- [x] Add info icon for country groups to show the list of the countries, when it hovers

-------------------------------
## Additional comments on 18th August

- [x] Sort by alphabet (Bar, or country groups, country).
- [x] Change shared and Global to Multi-country
- [x] Tooltip for treemaps.
- [x] Increase zoom level for overview treemaps.
- [x] Sort by alphabet view button.
- [x] Hover show label for Barcharts.
- [x] X number of actions from y number of countries.
- [x] Type of action first level on the overview.
- [x] Disable button for the download and loading.
- [x] Fix logic on the delete button on compare (group and country group).
- [x] If the value is zero on table compare, the number should be always "-".
- [x] Fix overview pie chart for pollutants.
- [x] Add count to Sankey type of charts.

---------------------

## Additional comments on 19th August

- [x] Fix country count in the second header bar.
- [x] Sort by value on Sankey type of charts.
- [x] Report Summary title to **Summary and Actions (2)**
- [x] Move All and Other to the Tail of the list.
- [x] Change second header bar counts to **X actions reported by Y countries**
- [x] Change contribution to *In-kind Contribution
---------------------

**P2**
--------------

- [ ] Reset button for the country filter.
- [ ] Split shared as a column in the comparison tab.
- [ ] Glossary and Support page.

**Comment by dedenbangkit** [comment]
**P1**
-------------
- [ ] Sort by alphabet (Bar, or country groups, country).
- [ ] Change shared and Global to Multi-country
- [ ] Tooltip for treemaps.
- [ ] Increase zoom level for overview treemaps.
- [ ] Sort by alphabet view button.
- [ ] Hover show label for Barcharts.
- [ ] X number of actions from y number of countries.
- [ ] Type of action first level on the overview.
- [ ] Disable button for the download and loading.
- [ ] Fix logic on the delete button on compare (group and country group).
- [ ] If the value is zero on table compare, the number should be always "-".
- [ ] Fix overview pie chart for pollutants.
- [ ] Add count to Sankey type of charts.

**P2**
--------------

- [ ] Split shared as a column in the comparison tab.
- [ ] Glossary and Support page.
