### ISSUE TITLE
table header not shown for Agri-business cluster in database tab

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#219]
<img width="1264" alt="Screenshot 2020-08-14 at 8 49 06 PM" src="https://user-images.githubusercontent.com/4419787/90251378-311e6380-de70-11ea-96f8-288aa126aa36.png">

**Comment by dedenbangkit** [comment]
<img width="1417" alt="Screen Shot 2020-08-17 at 7 03 44 PM" src="https://user-images.githubusercontent.com/3245109/90394196-6919e680-e0bc-11ea-9809-6278f5ad02ac.png">
