### ISSUE TITLE
Improvements webform tooltip 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#224]
Hi Joy,

For the webforms the information buttons are not working very well. Three things: sometimes the text is too wide for the screen which makes it difficult to read (1), there is an info button while there is no info given in the Flow question (2). The info buttons are mixed up, info of another question is given at the specific question (3). Do you know the causes and if we can improve this?

Registration webform: https://tech-consultancy.akvo.org/akvo-flow-web/greendeal/110030001
Monitoring webform: https://tech-consultancy.akvo.org/akvo-flow-web/greendeal/138000003  

---------------------------
In which question is point 2 being displayed ?
Mert:
-----
Monitoring --> 'Verkoop' tab --> question 8
It's only when the cursor is on the left bottom
Also Aanplant/Uitval question 11
When selecting 'uitval' in the first question

**Comment by dedenbangkit** [comment]
<img width="593" alt="Screen Shot 2020-08-20 at 9 58 31 PM" src="https://user-images.githubusercontent.com/3245109/90788744-4ee83e80-e330-11ea-986b-edec2ac4347b.png">
