### ISSUE TITLE
Webform does not respect double entry and min-max config for questions

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#227]

**Comment by dedenbangkit** [comment]
@joycarpediem, Note that this will be broken if we put **min > max** in the Flow Dashboard. Flow Dashboard allow to have **min-value > max-value**.

Example case:

```html
<input min="15" max="10"></input>
```

**Comment by joycarpediem** [comment]
Thats ok. Then it will just be an incorrect configuration
