### ISSUE TITLE
Webforms - cascade code missing from submissions

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-tech-consultancy#257]
Issue reported by 2Scale via support: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-399354-from-andrew-at-akvo-dot-org

When exporting the Data cleaning file the user found out that some submissions miss the code in the cascade answers. Valeria checked the cascade file on S3 and confirmed that the codes are properly saved in the file. After further looking at the data, it seems all submissions that miss the code were made via webforms. 

Here is the latest data export with the highlighted rows: https://drive.google.com/file/d/1-VEZMpsOJ4o4ACfkcsICMU8npPY8KWtl/view?usp=sharing

**Comment by dedenbangkit** [comment]
@janagombitova please close the issue once you confirm.

**Comment by janagombitova** [comment]
I cannot confirm as it would mean editing a partner dataset. But I told the partner and asked to let us know if they still have the issue. If they come back, I will reopen it. But for now, you guys confirmed it worked so I believe we can close it
