### ISSUE TITLE
Add crop table to home page

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#259]
https://docs.google.com/spreadsheets/d/1raOBiPt8YwNh1j7jps2ITuxYq63aKUtEpqkpRYETTzQ/edit#gid=0&range=A4
https://docs.google.com/spreadsheets/d/1raOBiPt8YwNh1j7jps2ITuxYq63aKUtEpqkpRYETTzQ/edit#gid=0&range=A5

**Comment by dedenbangkit** [comment]
Searchable table
