### ISSUE TITLE
Testing Contract: Akvo Flow form data structure and cascade resources

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-tech-consultancy#268]
## Context

The test will verify structural data on the **Akvo Flow XML** form and **SQLite cascade resource**.

1. Verify that all the objects match the **JSON conversion** of **the current XML form**.
    - [x] Create a test form that covered all types of questions in the **SEAP instance**.
    - [x] **Download the XML form** from Akvo Flow Instances. Please find the endpoints [here](https://github.com/akvo/akvo-tech-consultancy/blob/master/sites/akvo-flow-web-api/data/flow-survey-amazon-aws.csv). 
    - [x] **Unzip the file** and **convert it to JSON** using **[xmltodict](https://pypi.org/project/xmltodict/)**.
      Note that the xmltodict will convert children which don't have any sibling to an object instead of a list.
    - [x] Save the response of akvo-flow-web-api as json file for the source to compare.
2. Verify that **Cascade resource** matches the result from **Akvo Flow Web API**.
    - [x] **Download the SQL Lite Cascade** from Akvo Flow Instances. Please find the endpoints [here](https://github.com/akvo/akvo-tech-consultancy/blob/master/sites/akvo-flow-web-api/data/flow-survey-amazon-aws.csv), then save it as file for the source to compare.
    - [x] Using the form test from the first point. Find a cascade question then download the SQLite from S3.
    - [x] Match **the query from the SQLite** file to this endpoint:
 *https://tech-consultancy.akvo.org/akvo-flow-web-api/cascade/{instance_name}/{cascade_resource}/{id_of_parent}*
   Reference: https://github.com/akvo/akvo-tech-consultancy/blob/b13caf3f78c1512ee39c142540715786f65c34ef/sites/akvo-flow-web-api/app.py#L170
   Example: [https://tech-consultancy.akvo.org/akvo-flow-web-api/cascade/seap/cascade-296940912-v1.sqlite/0](https://tech-consultancy.akvo.org/akvo-flow-web-api/cascade/seap/cascade-296940912-v1.sqlite/0)

## Requirements

- Python 3.6
https://github.com/akvo/akvo-tech-consultancy/blob/b13caf3f78c1512ee39c142540715786f65c34ef/flow-api/Jobs_Uduma_ReportUpdate/Dockerfile#L1
- Testing Framework: **[Pytest](https://docs.pytest.org/en/stable/)**

## Repository
- Branch: **test/akvo-flow-form**
- Path: **https://github.com/akvo/akvo-tech-consultancy/tree/master/tests**
- Folder: **test-akvo-flow-form**
  - form: **/form**
  - cascde: **/cascade**

For the deployment method, *we will decide it later*.

**Comment by paulus-otto-harman** [comment]
as discussed with @dedenbangkit, dues are :

- questionGroup
- question > help
- question > help > altText
- question > validationRule
- question > validationRule - validationType
- question > validationRule - allowDecimal
- question > validationRule - minValue & maxValue
- question - cascadeResource
- question - localeNameFlag
- question - requireDoubleEntry
