### ISSUE TITLE
Inform user on trying to leave screen

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#340]
Do a dirty check

**Comment by joycarpediem** [comment]
Design :
If an iframe is loaded in the survey tab and the user is navigating away then show the following dropdown
"Please make sure that the data has been saved before you navigate away from the page. To save the data please click on the "Save" button in the questionnaire. 
Do you want to navigate away from the page ?
Click "Yes" if you have already saved the data
Click "No" if you have not saved the data
Yes  No

**Comment by punchagan** [comment]
@joycarpediem this can be closed, I think?
