### ISSUE TITLE
Need to find a way to assign a saved form to a user/member for projects 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#362]
Use case :
There is a project where 2 or more of the member organisations are involved. Org A and Org B

Org A starts the project , adds org B as a project partner
Now there are details of the project that Org A needs Org B to fill up or Org B needs to see what Org A is reporting on the project that they have executed together. Also so that both Org A and B don't report the same project

Current behaviour 
If org A start a submission , only users belonging to org A can view the submission 
Need to think of a way how we can create an assignment kind of feature where somebody from Org A can assign visibility/edit rights to somebody from org B

**Comment by loicsans** [comment]
https://xd.adobe.com/view/6eafcc35-23e4-4709-92e0-fd22bfe80703-3bfc/?fullscreen
A quick and easy way to add this functionality

**Comment by joycarpediem** [comment]
additional requirement :
The organisation which first creates and saves the submission is considered as "Parent"
Only parent can assign it to other org. The org that is assigned cannot further share it 
https://xd.adobe.com/view/6eafcc35-23e4-4709-92e0-fd22bfe80703-3bfc/screen/926ba0ff-11c0-4979-b6eb-7336d3460c4b/?fullscreen

**Comment by joycarpediem** [comment]
Notification 
Every user of the org that the submission is assigned to gets a notification email .

The text will be
Hi <User>
<Assigning User> from <Assigning Org> has added your organisation as a collaborator for  Project <Project Titles> .
You can now view and data to the saved project in your "previously saved forms" section in the GISCO portal. 

Please contact us via the feedback form in case you face any issues
