### ISSUE TITLE
Flow Web, Immutable vs Multi Immutable Dictionary Behaviour

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-tech-consultancy#42]
Server behaviour for image upload feature return [ImmutableDict response](https://github.com/akvo/akvo-tech-consultancy/commit/2b1064196b3ff3f8677d33628864e76ad6f0e71f) while in Local environment return [ImmutableMultiDict](https://github.com/akvo/akvo-tech-consultancy/commit/812058edc1adbe177c5e40a44bf140c9862473a2)

**Comment by joycarpediem** [comment]
Check with Puneeth to see if he has any ideas
