### ISSUE TITLE
Enable password protection for the 3 dashboards

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#48]

**Comment by merembablas** [comment]
Password are enabled. 
password file is in /home/tcakvo/.htpasswds/.iucn

@dedenbangkit if we re-deploy files, are the current .htaccess files in cpanel will gone too?

**Comment by dedenbangkit** [comment]
@merembablas, I'm afraid yes, but if no, we can also place it in a separate folder then copying it when we deploy it by editing the code deploy. Example:

```
ssh -i "${SITES_SSH_KEY}" \
    -p 18765 \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    tcakvo@109.73.232.40 'cp ~/public_html/xxx.htaccess ~/public_html/iucn/tof/.htaccess'
```

**Comment by dedenbangkit** [comment]
@merembablas, code deploy is [here](https://github.com/akvo/akvo-tech-consultancy/blob/master/sites/iucn/ci/deploy.sh)

**Comment by merembablas** [comment]
deploy.sh updated to copy .htaccess
