### ISSUE TITLE
Explore upload of PDF files to webforms

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#53]

**Comment by dedenbangkit** [comment]
@joycarpediem Upload to where? S3? I'm not sure about backend storage, because we use CI for the build and deploy. I'm afraid we will accidentally erase the data if we use backend storage.

**Comment by dedenbangkit** [comment]
Hi @iperdomo, could you please confirm if it's possible to upload a pdf file to S3 via the current Flow Mobile API (zip)?

**Comment by iperdomo** [comment]
Hi @dedenbangkit not sure what we're trying to do but the supported question types are:
`FREE_TEXT, OPTION, NUMBER, GEO, PHOTO, VIDEO, SCAN, DATE, CASCADE, GEOSHAPE, SIGNATURE, CADDISFLY` - There is no `PDF` or `BINARY_BLOB` supported.

More info at: https://flowsupport.akvo.org/article/show/30111-question-types

**Comment by dedenbangkit** [comment]
@iperdomo we are trying to push PDF file with PHOTO/VIDEO type of question, it returns 200 but we cannot find where the PDF file stored.

https://github.com/akvo/akvo-tech-consultancy/blob/master/sites/akvo-flow-web-api/app.py#L183

**Comment by iperdomo** [comment]
Looking at the code, it seems that we only support bulk-upload of zip files and images (.jpeg)

https://github.com/akvo/akvo-flow-services/blob/develop/backend/src/akvo/flow_services/uploader.clj#L83-L100

**Comment by iperdomo** [comment]
> @iperdomo we are trying to push PDF file with PHOTO/VIDEO type of question, it returns 200 but we cannot find where the PDF file stored.
>
> https://github.com/akvo/akvo-tech-consultancy/blob/master/sites/akvo-flow-web-api/app.py#L183

I was checking the code and the parameter i would suggest to adapt the parameter `resumableChunkSize` to match the value of `resumableCurrentChunkSize`
