### ISSUE TITLE
Add some context to the search page

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-tech-consultancy#75]
The current search page is very empty.
Does not guide the user around what can they look for

Add an over view about what is possible (embed something from CKAN ?)

**Comment by joycarpediem** [comment]
Add an "About the data library".
Navigation guide

**Comment by merembablas** [comment]
Add default data and info message if data not found

![Firefox_Screenshot_2020-02-22T06-37-34 036Z](https://user-images.githubusercontent.com/213163/75088226-f3094c80-557c-11ea-9b51-a15f999ef307.png)
![Firefox_Screenshot_2020-02-22T06-36-08 341Z](https://user-images.githubusercontent.com/213163/75088230-f4d31000-557c-11ea-87ee-ccdf84d34db7.png)

**Comment by dedenbangkit** [comment]
Commit reference: https://github.com/akvo/akvo-tech-consultancy/commit/fa944dc3928029693b3f2d99bec3ee3a0721cda0
