### ISSUE TITLE
Green Coffee Pricing Integration

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-tech-consultancy#8]
[Live Demo](https://drive.google.com/open?id=1RklOgJmyObooXQ47-EngGpm3WkS-DbcT)
------
![Imgur](https://i.imgur.com/JzorPMZ.jpg)
![Imgur](https://i.imgur.com/DVxWnk7.jpg)
![Imgur](https://i.imgur.com/8RFGqrI.jpg)

**Comment by joycarpediem** [comment]
Hi @dedenbangkit , it does not have to be so layman appropriate. This is meant for a future developer.

So we can have it maybe in the following structure

##Usecase
IPSARD collects daily about coffee price which are then displayed on the greencoffee app. They needed a mobile platform for their data collectors to collect the pricing information from various coffee markets in Vietnam......
##Steps
IPSARD sets up webservices for us to use
Separate surveys setup in Flow for each data collector. The primary difference in the surveys is the cascade for admin area(?)
The python script fetches data from flow 
........
##Known limitations/Issues
