### ISSUE TITLE
IUCN Plastics Conditional showing of result visuals

### ISSUE THREAD

**Issue by irenewestra** [akvo/akvo-tech-consultancy#80]
For the visuals on results framework (refer to Question 5 and 6, in group 'Outcome harvesting' of the survey), please implement conditional visibility based on the filter 'Project':

- If there is no filter on ‘Project’, the menu on the right shows both result visuals
- If a user chooses project Sida, it only shows the result visual referring to Question 5
- If a user chooses project Norad OR Primat, it only shows the result visual referring to Question 6

**Comment by merembablas** [comment]
Hi @irenewestra we implemented the conditional of result visual.

**Comment by irenewestra** [comment]
Thanks! This looks great.
