### ISSUE TITLE
IUCN Plastics X-axis labels result visuals incorrect

### ISSUE THREAD

**Issue by irenewestra** [akvo/akvo-tech-consultancy#81]
For both visuals on the result framework, please make the labels on the X-axis logical to what the bars are representing, e.g. in the screenshot attached the label should be "Output 2" and not "0"

![Screenshot 2020-02-20 at 14 05 58](https://user-images.githubusercontent.com/56399544/74928375-6cbd0100-53ea-11ea-858b-b133661a6141.png)

**Comment by merembablas** [comment]
Hi @irenewestra , I check Highcharts bar chart documentation, visual is correct. This is an example from Highcharts

![Firefox_Screenshot_2020-02-22T09-22-13 345Z](https://user-images.githubusercontent.com/213163/75124590-dd159c00-56e2-11ea-954e-f035ec9014f4.png)

Label in the bottom is represented by its color in the chart. Maybe, category **"0"** makes it confusing. Currently, I change the category to **"results"**

![Firefox_Screenshot_2020-02-22T09-22-48 450Z](https://user-images.githubusercontent.com/213163/75124657-4a293180-56e3-11ea-8931-d4643cdc93da.png)

**Comment by irenewestra** [comment]
But if multiple type of Outputs are added, it does not make sense to have one bar saying "results". E.g. the bars that will show when all answers are input once are Output 1, Output 2, Output 3, etc.

**Is it otherwise possible to change the chart type to pie chart?** Then we do not have this labelling issue anymore.

**Comment by merembablas** [comment]
Yes, we updated bar to pie chart.

**Comment by irenewestra** [comment]
Thanks for the quick fix :-)
