### ISSUE TITLE
IUCN Plastics Change results chart titles

### ISSUE THREAD

**Issue by irenewestra** [akvo/akvo-tech-consultancy#82]
To prevent duplication of chart titles:

- For Question 5 of Outcome Harvesting, change chart title to: Link to MAREPLASTICCS result framework
- For Question 6 of Outcome Harvesting, change chart title to: Link to PWFI result framework
(TLDR; Rename the two chart titles to the actual question titles)

**Comment by merembablas** [comment]
Hi @irenewestra , we fixed the issue. Could you please check and close this issue.

**Comment by irenewestra** [comment]
Checked. Looks OK!
