### ISSUE TITLE
IUCN Plastics Chart missing + Rename titles 

### ISSUE THREAD

**Issue by irenewestra** [akvo/akvo-tech-consultancy#83]
On the tab '**Activity**' there seems to be a chart missing, for Question 8 of question group 'Main group' in the survey. Please create the same chart as for Question 7 (the chart currently named 'Subject').

If the chart is indeed missing and you end up with two charts, please name:

- The existing chart for Main Group, Question 7: Link to MAREPLASTICCS result framework
- The new chart for Main Group, Question 8: Link to PWFI result framework
(TLDR; Rename the titles to the actual question titles)

**Comment by merembablas** [comment]
Hi @irenewestra we fixed the chart missing, and rename titles.
