### ISSUE TITLE
IUCN Plastics Country dropdown incorrect

### ISSUE THREAD

**Issue by irenewestra** [akvo/akvo-tech-consultancy#84]
When selecting 'Sida MARPLASTICCS' under 'Project', the 'Country' drop down on the right shows **twice Thailand**, but **misses Vietnam.**

![Screenshot 2020-02-21 at 07 41 51](https://user-images.githubusercontent.com/56399544/75004944-e225e180-547d-11ea-9552-c0f0cb9db405.png)

**Comment by merembablas** [comment]
Hi @irenewestra  , we fixed the issue. Could you please check and close this issue.
