### ISSUE TITLE
IUCN Plastics Error in conditionality of charts

### ISSUE THREAD

**Issue by irenewestra** [akvo/akvo-tech-consultancy#86]
On the **Activities tab**: For the charts on the two results framework, if NO specific project is selected you see both charts on the right. This is correct. However, there are currently **no** activity survey entries for the PWFI framework, but when project filter is on ALL it shows 2 entries for PWFI. 

Please check how this can occur. When selecting NORAD/Primat project, the PWFI chart is empty (which is correct). So issue only appears when project filter is on ALL.

![Screenshot 2020-02-24 at 10 36 52](https://user-images.githubusercontent.com/56399544/75135872-f541e700-56f3-11ea-9139-89cbb57d730e.png)

**Comment by merembablas** [comment]
Hi @irenewestra , we fixed the issue.
