### ISSUE TITLE
API Test Case Contract

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-tech-consultancy#99]
# CONTEXT

Develop several test cases of the API input data values which we enter in the system along with the expected results.

1. Authentication methods specs:
    - Auth0
    - KeyCloak
    - RSR Token
2. Akvo Flow specs:
    - [Akvo Flow Rest API](https://github.com/akvo/akvo-flow-api/wiki/Akvo-Flow-REST-API)
    - [SyncAPI](https://gist.github.com/iperdomo/b507b84f58f9cfcfa114b9ccdb77aadd).
    - Akvo Flow XML Questionnaire (S3)
    - [Akvo Flow Data Model](https://github.com/akvo/akvo-flow/wiki/Data-Model)
    - Akvo Flow Zip Survey Upload, @iperdomo could you please inform the link to the gist / issue?
    - Akvo FLow Zip Image Upload.
3. Akvo Lumen specs:
    - Trigger Update API Endpoint.
    - List of Dashboard, Datasets, Visualisation Endpoints.
    - Datasets Endpoint.
4. Akvo RSR specs:
    - [Akvo RSR Partner API Read](https://github.com/akvo/akvo-rsr/wiki/RSR_Partner-API-Read)
    - [Akvo RSR Partner API Write](https://github.com/akvo/akvo-rsr/wiki/RSR_Partner-API-Write)

# PLAN

- Develop the ReadAPI test (the NodeJS test framework (Karma / Jasmine).
- Develop Zip upload to Akvo Flow test (Pytest).
- Develop Test case for Survey submission (Cucumber).

**SUPPORTING DOCS**
- [Akvo Flow New API](https://github.com/akvo/akvo-flow-api/wiki/Akvo-Flow-Sync-API)

**Comment by joycarpediem** [comment]
@dedenbangkit , we can remove keycloak, as we will soon stop using .

**Comment by dedenbangkit** [comment]
@joycarpediem, then we should change all the jobs which are still using keycloak to auth0. Currently, we have several e-mails which not registered to the auth0 client yet.
